baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
themesDir = "themes"
theme = "hyde"

name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = "Josh Rollins"
    homepage = ""

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
