baseurl = "https://jarss.github.io/TAONAW/"
publishDir = "docs"
languageCode = "en-us"
title = "The Art of Not Asking Why"
themesDir = "themes"
theme = "hyde"


name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "hara kiri"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = "Josh Rollins"
    homepage = ""

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"

[params]
    description = "Tech, Life, and  the Stuff in Between."
    themeColor = "theme-base-0a"